language: node_js
node_js:
- stable
services:
- postgresql
cache:
  directories:
  - node_modules
before_script:
- psql -c 'create database descartes;' -U postgres
script:
- npm test
after_success:
- npm run coverage
env:
  matrix:
    secure: EhgivZwyI7XiluJ80S+qNSnChv+Y5aE5cwxdhUwqLoRlNhR/WStrXcAof7upIdFP72jdMCoynJHzrS73HyrscBOPHNni5/TjVLpjOtOQAbwhCZUj+pAfSD+fyIzfxczBJ+nnsxyR6b7YUiArdTM+9t9nXd2XiJKK3mzxnivvsTHMSuolAICfa04722Prxt80YcFOKV/gm+ht4ozHlfB9wCPguW1zbluTkhjpJDQycHJHP8PvSCOFLNqarayKmLCnNDgNkXapVfnJlGymGJ3mDZEn6MCiUY+5IFY1AoWed7IDb/RYwzajX2WPCo1JnyFsFRuDEDkhYEbsqPsIRV68hm+/ZON80l5t/bqwgVEm9lWQnozhfGJ+rWtA3QG2+hGKkPLaAewksMtXbXql350wn7Bt6IpOl/y1lbCn776G1NoIZp2VUIQIDG4EuCMrrWZe2vsITxwENDWE+7btcWSGQ3W/RV/nLZzP/4mj5U7i+F8DGuqryNCsy/rF9p4LkELPcjOtxUgZ/hvXHZ5Ie6U9ZsPaYcmCXsKjlTe6uwy/uGCIMizzqOIw04G2CjK8XXBzAV/1X/bm9jpDRAs/kOuy8tdhTt7STXx67AAXikSHyggMky5jeCRI+5jeAvmwYPv8yGSRtGdvm1hHz8a1q64YI1UgKtvM22wuUAnVPY5uuQ4=
