language: node_js
node_js:
- stable
services:
- postgresql
cache:
  directories:
  - node_modules
before_script:
- psql -c 'create database descartes;' -U postgres
script:
- npm test
after_success:
- npm run coverage
env:
  global:
  - secure: Kj4lZUtnv4MfhFlw8z6ZLcDFKn9hE2Dg1c0sC1xvskSUs9+EHshAumL8AcHC4AAy6SA7I+X3kXPvtS18Dp8ZW1e4ZhwHknEWPp7j3+W41dMb4Hr6paW1wJcucF7L3bDBFrOY/h4h8Xj5sDbxFQhr7Ovpwazu4t5whm/TocfziobDWHyhpqo1dKU5b91Y9J7LwQviACiZ6RlyliKruYkJ/VtdYJ4LZq35hYDZ/375HRfEGWkzV0m8KorV+X2fqAX/oHIk5nUm1yJl6XF/2p+d+E8b7lYXqobmB9gxGKcbHXq+oSr0nHinYzqmFCSuYiwHgk//YokYTI4WiAQ1kimv8oojJ+GgPnd38VUg/fqz+SA5Jj++a7rz6Tzta9HogfC+WKQvRbIpvdvLOBGWOl65ktkTxVjmoSNmZxzNdZcmGNdlgyFe/arRf9DQE99XMjmBO/t/8MXoYT4MHOqdZc7zfk9DZpDU3yzmq4OaFxIy2U9XZCSIYYPquHabw00X+OLU6bC5wkoyviXZUW4ux2oG0Rukgu8gc5vz0iZWkhLz//88wx+RlMm9Q0+tXUYD/qvf4oSPHiU9V8eMv5Sjsb7DOBHWEgRkN6TIU18IsXqd0zeSvFuPZKaeCiW+HQTO5NHRtHr1bz/y2ygdwHJUqTNT7y9QI1k0ltd4AZuU9YZdpw0=
  - secure: JEHgczkNA/B8gZbYF6XD4TrM6dX+nHp4dxaFQ4DSf/6fK+wve81HBUfPGiN9/dlDnrP0pDFRXkRy7yrSMeX1wZsaZlOBq7rgramhh9UjG0qkvLAbbd1Q5FRdt59Ai4MO/n1fA//3dA5k3hHXVFYVI3oXI1bi/lNizOuJaIHW02dRcrCnpTTRvm9AFF+9OPwq7Hkgh0W5e3Zi/Mn/QZLDBuOyslTACg+9l2ED43BREF4wgK8fJnJko85I0yk/7qBbWCIO+zDlpFiawjnouPK3hohTjnKBOYhH+urcVQO1B5vpb3cRH6OiSBKTZBn2IqmXEvcZDg86UxdyCQqfUN2DCsH/V5fpVpQQlF0iO3xGai2NP8ncXSWdJPsyq4wSahMIFiQPH2XE+VTNKG6ambsEp6KcP/0m/o7H/gX3VFFMJvPvmv+6Iz5LZBBvmP4zWXt6F5LNPO2JoKEIYs0NeqXzXh4XDlPWwK65vq+Ci0cCUlgCcP9Q4USbGO3jQelNpxL1Dt/2Zwl+qAS+enPqD2/S8WYYKPTvsqE+G6gl42l40Ttsan8UD77agNrgb3JHGtn3LkhukgmTfMKqYxXHdzhpLlj6q0hzcsvWTcc0+K7b3WQ8e7zTg2BDJHlKBtGRfMedn8ujBm2lvUb9fkZtHBKW2O0RVGTd9WWwaYN48S1vtsM=
  - secure: 03H8tY1sFdmJuKJ1LKwvk9kTcxF/h73beZo3M01St+XhmIjldTliJgmQF6Lu6B+1q8ZxCAtZWEfEeRQK6TeFEZLxtFnQXm3/8znK5IhQS2NL+P847s9mZvGmvZ1JMtt2zwlbknjKjgwA3MX1TWTwGvBVRzPu2Di1TNhjR2mnazu4Zq+9FI+iuTjUCW8VCzdi9pB9c+zEc5YF7eu5Qu8JFaUduCKzQmCPdIal71LcubV/7gApVnzHaXqJews9yYZqO58Gwbmcj9mRAf4oRrS5A+T7AQlcY89JCgqY4oDKSYRpWHITZhtlcFkojaYI1GBc6Vo3iCrDhvcz9TUuXqiAdWNL5mOQUq9MnfiNs3umaPlZzjLbLRjKI81yaZ3CewTEJZD+ztbEDJLNUCxrsf3838NeDiR0RmPtq31VwNeYyZgJFixSAnJVi1g1yxqBnxYMWsVput2/a8z+NhsilqUHvbCxHSzk1DJRuMk5XRII1K9j9Sm/hnn0G09ZwrDfuk3rtA2gw6qyuDFpKDD7P9PAMAoeqbPYtVk2KnkcZekRM+phZLXu7AZWyjRCT0kxFj9XyzDIUyy3Rw7YlcK6Oe1gM8OWUcW7irERmiwT/K38kEfNn9o8gj1g3wHQmWHRIzYA3opoTRu7WbO/mVCaBhApsFUzvuN2X2hi8xrBWvdbSco=
