language: node_js
node_js:
  - "stable"
services:
  - postgresql
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database descartes;' -U adityapillai
script:
  - npm test