language: node_js
node_js:
- stable
services:
- postgresql
cache:
  directories:
  - node_modules
before_script:
- psql -c 'create database descartes;' -U postgres
script:
- npm test
after_success:
- npm run coverage
env:
  matrix:
    secure: H+RkTDAxdwPbLOrFeeAjWL4mHwjpUI9njUpquq2z2e54UsDUUljlcyPDLFwLEG1byvTaN/yeLySR4e4MMVc39oUij5+k/HXIqRO552kV6ZQWR3IaF1xxPydGQVbNRpkQMXpO+Go2H9P63z5UmVmQt94+G6L7GIheb5ZT0PbmnW/cZ4CkfDlfgRPaN2lLSCM4iLcMYWaKIaHuKoePQ++yHH+thTXk9+IA3V3ml+twQWd4NSVHQG0qF2CsEgZkDXflUJ4hMnX6pzrNXPNR5hkrh8oCqJrWE4mny1QhOHXRW+5m6N9e5nxG8XFdxvlficTSvCpsjJ1oYcenWCrRFrDkeJ1Gu/9PrXDvuMwvVMvORfYWGQHYu/c82yebhnNMBDworIwztaXkv25mkc4CGJHF3NZdJ90DzJyR1Q4IBpQ7BQ/z3AKgsXPnXNQAl1CqBnyGDt77IM6UmXiU8RJFvfrdhTnzpkyW3Ha4GE4MDVaszqHMOTxJJItQYSrHPjN4xlbvR7efanPtUuIQhvUfbTUq+AhwPID/28qOWqK4l4haGuH8YhykgZPYUsAguWXqGOWNR+CQSSL6fwnS0WZDekx8O14gR1pHzQdTGckL7iVcJuMQcBzIjMk3SEfhVHwiUI/VjwLWXWnZgo2L+AanO1u+Ty+R9dcgA+xHmS+qgFxkZhI=
